fragment VariantLinkageDisequilibrium on LinkageDisequilibrium {
  id
  variantId
  variantRsId
  variantPosition
  r2
  dPrime
  egCellTypes
  egGenes
  mostSevereConsequence
}
query VariantLinkageDisequilibrium($variantId: String!) {
  linkageDisequilibriumsForVariant(variantId: $variantId) {
    ...VariantLinkageDisequilibrium
  }
}
