fragment VariantLinkageDisequilibrium on LinkageDisequilibrium {
  variantGnomadId
  variantRsId
  r2
  dPrime
  egCellTypes
  egGenes
  mostSevereConsequence
}
query VariantLinkageDisequilibrium($variantId: String!) {
  linkageDisequilibriumsForVariant(variantId: $variantId) {
    ...VariantLinkageDisequilibrium
  }
}
