fragment VariantPageEnhancerGenePrediction on EnhancerGenePrediction {
  id
  score
  cellType
  score
  variantToGeneDistance
  enhancerStart
  enhancerClass
  enhancerEnd
  targetGeneTss
  enhancerToGeneDistance
  pip
  model
  dataset
  isTemporary
  datatrackURL
  targetGene {
    id
    symbol
  }
}
fragment VariantPageBpnetPrediction on BpnetPrediction {
  id
  logfc
  logfcPval
  jsd
  jsdPval
  maxPercentile
  logfcMaxPercentile
  logfcMaxPercentilePval
  allele1PredCount
  allele2PredCount
  allele1TFFamily
  allele2TFFamily
  allele1Motif
  allele2Motif
  cellType
  dataset
  isTemporary
}
query VariantPage($variantId: String!) {
  genesForVariantSchema {
    qtls {
      id
      sourceId
      sourceLabel
      sourceDescriptionOverview
      sourceDescriptionBreakdown
      pmid
      tissues {
        id
        name
      }
    }
    intervals {
      sourceId
      sourceLabel
      sourceDescriptionOverview
      sourceDescriptionBreakdown
      pmid
      tissues {
        id
        name
      }
    }
    functionalPredictions {
      id
      sourceId
      sourceLabel
      sourceDescriptionOverview
      sourceDescriptionBreakdown
      pmid
      tissues {
        id
        name
      }
    }
    distances {
      id
      sourceId
      sourceLabel
      sourceDescriptionOverview
      sourceDescriptionBreakdown
      pmid
      tissues {
        id
        name
      }
    }
  }
  genesForVariant(variantId: $variantId) {
    gene {
      id
      symbol
    }
    overallScore
    qtls {
      sourceId
      aggregatedScore
      tissues {
        tissue {
          id
          name
        }
        quantile
        beta
        pval
      }
    }
    intervals {
      sourceId
      aggregatedScore
      tissues {
        tissue {
          id
          name
        }
        quantile
        score
      }
    }
    functionalPredictions {
      sourceId
      aggregatedScore
      tissues {
        tissue {
          id
          name
        }
        maxEffectLabel
        maxEffectScore
      }
    }
    distances {
      typeId
      sourceId
      aggregatedScore
      tissues {
        tissue {
          id
          name
        }
        distance
        score
        quantile
      }
    }
  }
  indexVariantsAndStudiesForTagVariant(variantId: $variantId) {
    associations {
      indexVariant {
        id
        rsId
      }
      study {
        studyId
        traitReported
        pmid
        pubDate
        pubAuthor
        hasSumstats
      }
      pval
      nTotal
      overallR2
      posteriorProbability
      oddsRatio
      oddsRatioCILower
      oddsRatioCIUpper
      beta
      betaCILower
      betaCIUpper
      direction
    }
  }
  tagVariantsAndStudiesForIndexVariant(variantId: $variantId) {
    associations {
      tagVariant {
        id
        rsId
      }
      study {
        studyId
        traitReported
        pmid
        pubDate
        pubAuthor
      }
      pval
      nTotal
      overallR2
      posteriorProbability
    }
  }
  variantInfo(variantId: $variantId) {
    enhancerGenePredictions {
      ...VariantPageEnhancerGenePrediction
    }
    bpnetPredictions {
      ...VariantPageBpnetPrediction
    }
  }
}
