query DataTracksTable {
    getDataTracks {
       id
       cellTypeId
       cellType
       study
       studyId
       paperUrl
       dnaseSignalUrl
       atacSignalUrl
       e2gPredictionsUrl
       variantPredsUrl
       elementsUrl
       modelType
    }
}

